#!/bin/bash
# Удаление всех файлов с указанным суффиксом при наличии файлов с теми же именами,
# но с другим заданным суффиксом
# bash -x
if [[ $1 == "?" ]]; then
	echo -ne "Программа получает на вход суффикс, далее она создаёт список файлов temp с указанным суффиксом.\n"
	echo -ne "Список temp обрабатывается так, что в нём остаются только имена файлов. Далее создаётся список other из файлов \n"
	echo -ne "с отличными суффиксами от указанного. После чего программа заходит в цикл по списку temp и при наличии хотя бы \n"
	echo -ne "одного совпадающего имени у temp и other удаляет ВСЕ файлы с исходным суффиксом.\n"
	exit 0
fi

# Задание суффикса через флаг для первого условия
while getopts ":s:" opt; 
do
	case $opt in
		s)
				suf="$OPTARG";;
		*)
			echo "Вы ввели неизвестный флаг. Введите \"./lab21.sh ?\" для справки"; 
			exit 1;;
	esac
done

# Проверка на пустой символ
while [[ -z $suf ]] 
	do
		echo "Введите суффикс: "
		read suf	
	done

# Добавление точки к суффиксу	
suf="`echo .`$suf"

echo "Создание списка файлов temp с указанным суффиксом $suf: "
find -name "*$suf" | xargs -l echo > temp
cat temp

echo "Удаление ./ в начале и $suf в конце для temp (необходимо для сравнения имён): "
cat temp | sed "s/..//" | sed "s/$suf//" | xargs -l echo > temp
cat temp

echo "Создание списка файлов other с суффиксами, отличными от $suf"
find ! -name "*$suf" ! -name "temp" ! -name "." ! -name "other" ! -name "all" | xargs -l echo > other
cat other

echo "Удаление всех файлов с $suf при наличии хотя бы одного совпадающего имени"
#считывает первую строку как x в temp, ищет такое же имя через grep, затем удаляет ВСЕ файлы с указанным суффиксом
#иначе не делает ничего
while read x
        do
		cnt=`cat other | grep "^./${x}\b" | wc -l`
                if  [[ cnt -ne 0 ]]
                        then
				find -name "*$suf" -delete
                                break
                        fi
        done < temp

echo "Чистка мусора: удаление списков temp и other"
rm temp other
